on: 
 workflow_dispatch:
name: Generate docs
jobs:
 git-bat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Bijou
        uses: actions/checkout@v2
        with:
          repository: Bijou-js/bijou.js
          path: bijou
          ref: main
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: sudo npm install --save 
      - run: npm run doc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Docs Generated
